version: '2'

services:

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootp
    ports:
      - 3306:3306
    volumes:
      - "./scripts/db:/docker-entrypoint-initdb.d"

  cardvert:
    image: "scout24/cardvert:latest"
    environment:
      - CARDVERT_HTTP_HOST=cardvert
      - CARDVERT_HTTP_PORT=80
      - CARDVERT_DB_HOST=mysql
    ports:
      - 8080:80
